mychan/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('obiadekchan/', include('obiadekchan.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

obiadekchan/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'obiadekchan'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ThreadView.as_view(), name='thread'),
    path('mode/', views.ModeratorView.as_view(), name='mode'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('banned/', views.banned, name='banned'),
    path('history/',views.history,name='history'),
    path('q/<int:pk>', views.linking),
    path('ajax/posts/<int:pk>', views.ajaxPostPreview, name='ajax_post_preview')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

obiadekchan/models.py
from django.db import models
import os
# Create your models here.
def file_name(instance, filename):
    org_name, file_ext = os.path.splitext(filename)
    #new_naem = 'img_' + str(instance.id)
    instance.rep_reason = org_name + file_ext
    return 'chanImgs/{naem}{ext}'.format(naem = org_name, ext= file_ext) 

class Post(models.Model):
    thread_pos = models.IntegerField(default=1)
    # pub_date = models.DateTimeField(auto_now_add=True)
    op_email = models.CharField(null=True, max_length=20, blank=True)
    post_title = models.CharField(null=True, max_length=20, blank=True)
    post_body = models.TextField()
    ip_address = models.GenericIPAddressField(protocol='IPv4')
    image = models.ImageField(upload_to=file_name, blank=True, null=True)
    rep = models.BooleanField(blank=True, default=True)
    rep_reason = models.CharField(null=True, blank=True, max_length=20)
    banned = models.BooleanField(blank=True, default=True)
    count = models.IntegerField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    rep_res = models.CharField(
        null=True, blank=True, default='No reason provided', max_length=200)
    password = models.CharField(max_length=20, null=True, blank=True)
    replies = models.ManyToManyField(
        'self', blank=True, related_name='threadd')
    is_thread = models.BooleanField()
    is_op = models.BooleanField(null=True, blank=True)
    is_mode = models.BooleanField(null=True, blank=True)
   # edited = models.DateTimeField(auto_now=True,blank=True,null=True)

    def extension(self):
        name, extension = os.path.splitext(self.image.name)
        if extension.lower() == '.gif':
            return True
        else:
            return False


class Banned(models.Model):
    ip_ad = models.CharField(null=True, max_length=20)
    length = models.DateTimeField()
    reason = models.CharField(null=True,max_length=100)
    post_content = models.TextField(null=True,blank=True)

class Misc(models.Model):
    thread_count = models.IntegerField()
    # post_count = models.IntegerField()

obiadekchan/forms.py
from django import forms
from django.db import models
from .models import Banned, Post
from bootstrap_modal_forms.forms import BSModalForm


class addPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['op_email','post_title','post_body','image','password']
        widgets = {
            'password': forms.HiddenInput(),
    }

class banForm(forms.ModelForm):
    class Meta:
        model = Banned
        fields = ['length','reason']
        widgets = {
            'length': forms.DateTimeInput(),
        }

obiadekchan/views.py
from django.contrib.auth import authenticate
#from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from pathlib import Path
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic, View
from django.views.generic import TemplateView
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.contrib import messages 
from .models import Banned, Misc, Post
from .forms import addPostForm
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import FormView
from django.contrib.auth.decorators import login_required
import datetime
from django.utils import timezone
from django.core.paginator import Paginator
from .utils import checkBan, bumpThread, incrementPostCount
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.http import JsonResponse



# Create your views here.

banned_ips = []



class IndexView(View):
    template_name = 'obiadekchan/index.html'
    q2 = Post.objects.filter(is_thread=True).order_by('-id')
    for q in q2:
        num = len(q.replies.all())
        q.answers = list(q.replies.all())[-3:]
        if num > 3:
            q.hidden = num - 3
    def get(self, request, *args, **kwargs):
        q2 = Post.objects.all().filter(is_thread=True).order_by('-thread_pos')
        for q in q2:
            num = len(q.replies.all())
            q.answers = list(q.replies.all())[-3:]
            if num > 3:
                q.hidden = num - 3
        #q2 = Thread.objects.all().prefetch_related('thread_ans').order_by('-thread_pos')
        paginator = Paginator(q2, 10)
        page = request.GET.get('page')
        q3 = paginator.get_page(page)
        context = {'q2': q3, 'form': addPostForm()}
        return render(request, 'obiadekchan/index.html', context)

    def post(self, request, *args, **kwargs):
        form = addPostForm(request.POST, request.FILES)
        if request.method == 'POST':
            if 'post_thread' in request.POST:
                t_c_object = Misc.objects.first()
                if t_c_object is None:
                    t_c_object = Misc.objects.create(thread_count=0)
                if form.is_valid():
                    from django.db.models import Max, Min
                    from ipware import get_client_ip
                    result = Post.objects.all().aggregate(Max('thread_pos'))
                    xpkej = form.save(commit=False)
                    xpkej.thread_pos = bumpThread(result)
                    ip_address = get_client_ip(request)
                    xpkej.ip_address = ip_address
                    if checkBan(ip_address):
                        return HttpResponseRedirect(reverse('obiadekchan:banned'))
                    thread_count = t_c_object.thread_count
                    t_c_object.thread_count = thread_count + 1
                    if t_c_object.thread_count > 50:
                        det = Post.objects.all().filter(is_thread=True).order_by('-thread_pos').first()
                        det.delete()
                        t_c_object.thread_count = t_c_object.thread_count - 1
                    xpkej.is_thread = True
                    xpkej.count = xpkej.id
                    if 'is_mode' in request.POST:
                        xpkej.is_mode = True
                    xpkej.password = request.POST.get('password')
                    t_c_object.save()
                    xpkej.save()
                    mail = request.POST.get('op_email')
                    if mail.lower() == 'noko':
                        return HttpResponseRedirect(reverse('obiadekchan:index'))                    
                    return redirect('obiadekchan:thread',pk=xpkej.id)
                else:
                    q2 = self.q2
                    return render(request, self.template_name, {'form':form, 'q2': q2})
            elif 'delete_posts' in request.POST:
                del_posts = request.POST.getlist('rep_choice')
                for i in del_posts:
                    post = Post.objects.get(pk=i)
                    pwd = request.POST.get('password')
                    if post.password == pwd:
                        post.delete()
                return HttpResponseRedirect(reverse('obiadekchan:index'))
            elif 'report_post' in request.POST:
                rep_posts = request.POST.getlist('rep_choice')
                #post = Post.objects.get(pk=request.POST['rep_choice'])
                for i in rep_posts:
                    post = Post.objects.get(pk=i)
                    post.rep = False
                    post.rep_res = request.POST.get('r_reason')
                    post.save()
                return HttpResponseRedirect(reverse('obiadekchan:index'))
            
            
class ThreadDetail(generic.DetailView):
    model = Post
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = addPostForm()
        q2 = Post.objects.filter(is_thread=True).order_by('-thread_pos')
        for q in q2:
            q.answers = list(q.replies.all())
        return context

class ThreadPost(TemplateView):
    template_name = 'obiadekchan/thread.html'
    model = Post


    def get_object(self, *args, **kwargs):
        thread = get_object_or_404(Post, pk=self.kwargs['pk'])
        return thread

    def post(self, request, *args, **kwargs):
        form = addPostForm(request.POST, request.FILES)
        if 'post_reply' in request.POST:
            if form.is_valid():
                t_form = form.save(commit=False)
                thread = get_object_or_404(Post, pk=self.kwargs['pk'])
                #t_form.Thread = thread
                from django.db.models import Max
                from ipware import get_client_ip
                ip_address = get_client_ip(request)
                t_form.ip_address = ip_address
                if checkBan(ip_address):
                    return HttpResponseRedirect(reverse('obiadekchan:banned'))
                result = Post.objects.all().filter(is_thread=True).aggregate(Max('thread_pos'))
                mail = request.POST.get('op_email').lower()
                if mail == 'sage':
                    thread.thread_pos = thread.thread_pos
                else:
                    thread.thread_pos = bumpThread(result)
                #t_c_object = Misc.objects.first()
                #t_form.count = len(thread.replies.all())+1
                t_form.is_thread = False
                t_form.date = timezone.now()
                if 'is_mode' in request.POST:
                    t_form.is_mode = True
                t_form.password = request.POST.get('password')
                if 'is_op' in request.POST and thread.password == t_form.password:
                    t_form.is_op = True
                t_form.save()
                thread.replies.add(t_form)
                thread.save()
                if mail.lower() == 'noko':
                    return HttpResponseRedirect(reverse('obiadekchan:index')) 
                return redirect('obiadekchan:thread', pk=self.kwargs['pk'])             
        elif 'report_post' in request.POST:
            rep_posts = request.POST.getlist('rep_choice')
            #post = Post.objects.get(pk=request.POST['rep_choice'])
            for i in rep_posts:
                post = Post.objects.get(pk=i)
                post.rep = False
                post.rep_res = request.POST.get('r_reason')
                post.save()
            return HttpResponseRedirect(reverse('obiadekchan:index'))
        elif 'delete_posts' in request.POST:
            del_posts = request.POST.getlist('rep_choice')
            for i in del_posts:
                post = Post.objects.get(pk=i)
                pwd = request.POST.get('password')
                if post.password == pwd:
                    post.delete()
            return HttpResponseRedirect(reverse('obiadekchan:index'))


class ThreadView(View):

    def get(self, request, *args, **kwargs):
        view = ThreadDetail.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = ThreadPost.as_view()
        return view(request, *args, **kwargs)


class ModeratorView(View):

    #login_url = 'obiadekchan/login'
    #redirect_field_name = 'redirect_to'
    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        template_name = 'obiadekchan/mode.html'
        context = {'posts': Post.objects.all().filter(rep=False),
                   'banned': Banned.objects.all()}
        return render(request, template_name, context)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            from ipware import get_client_ip
            if 'del_post' in request.POST:
                post = Post.objects.get(pk=request.POST['del_post'])
                post.delete()
                t_c_object = Misc.objects.first()
                t_c_object.thread_count = t_c_object.thread_count - 1
                t_c_object.save()
                return HttpResponseRedirect(reverse('obiadekchan:mode'))
            elif 'ban_ip' in request.POST:
                post = Post.objects.get(pk=request.POST['ban_ip'])
                ip_address = post.ip_address
                b_reason = request.POST.get('b_reason')
                b_length = request.POST.get('b_length')
                content = post.post_body
                ban = Banned.objects.create(ip_ad=ip_address, reason=b_reason, length=b_length, post_content=content)
                return HttpResponseRedirect(reverse('obiadekchan:mode'))
            elif 'unban' in request.POST:

obiadekchan/templates/obiadekchan/bane.html
{% load static %}
<html>
        <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
                <meta name="description" content="">
                <meta name="author" content="">
                <link rel="icon" href="../../favicon.ico">
                <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/navbar-fixed-top/">
            <link rel="stylesheet" href="{% static 'css/styles.css' %}">
             <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

             <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
             </head>
             <body>
                 {%if ban%}
                 {%for bane in ban%}
                 <div class='container' style='margin-top:150px'>
                 <p>Zgryzota?</p>
                 <p>Ban reason: {{bane.reason}}</p>
                 <p>Banned until: {{bane.length}}</p>
                </div>
                {%endfor%}
                {%else%}
                <center>
                <div class='container' style='margin-top:150px'>
                <p>The wicked flee though no one pursues, but the righteous are as bold as a lion.
                    </p></div></center>
                    {%endif%}
          
             </body>>

obiadekchan/templates/obiadekchan/catalog.html
{% extends 'base.html' %} {% load static %}
<html>
<head>


</head>
<body>
<p>Under development.</p>






</body>
</html>

obiadekchan/templates/obiadekchan/history.html
{% extends 'base.html' %} {% load static %}
<html>

<head>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->

    <style>

    </style>
</head>

<body >
    {%block body%}
    {%load thumbnail%}

    {% regroup posts by ip_address as users %}
    {% for user in users%}
    <div class="container">
        <div class="container-heading"><h4><b>{{ user.grouper }} Click to show all posts made by this user.</b></h4>
        <div class='hidden'>
        {% for answer in user.list %}
        <div class='constainer' style='  color:black;  display: inline-flex; boarder:solid; border-radius: 5px; baorder-color: darkgoldenrod; background: #ACD7DE;
        max-width: 50%; margin-bottom:0.4%;
    margin-left: 1%;'><div classs='post' style='padding: 5px;
    display: inline-block;
    ;'>
    <div class='answer_title'><input type='checkbox' name='rep_choice' value='{{answer.id}}'></input>{%if answer.post_title %}<span class='title'> {{answer.post_title}}</span> {% endif %}{%if z.is_mode%}
        <span style='color:#65CC2D;font-weight: bold;'> ☘️Moderator</span> 
        {%else%}  {%if answer.email%}
        <a href='mailto:{{answer.email}}'>Anonymous</a> {%else%}
        <span class='name'> Anonymous</span> {%endif%}{%endif%}{%if answer.is_op%}<span style='color:darkred;font-weight: bold;'>(OP)</span>{%endif%}
        <span class='date'> {{answer.date}} </span>
        <span class='post_number'> post number: <a href='#'>{{answer.id}}</a> </span></div>
    {%if answer.image%} {%thumbnail answer.image "240" as ima %}
    <div class='answer_img'>
        <a href='{{answer.image.url}}' target="_blank" style='    float: left;
      margin: 2%;
    
    
       posiation: relative; display: flex; 
    '><img src='{{ima.url}}' /></a>
    </div>
    {%endthumbnail%} {%endif%}
    <div class='p_body'><pre style='margin-block-start: 1em;
                margin-block-end: 1em;     white-space: pre-wrap;  
                margin-inline-start: 40px;padding-left: 3%;
                margin-inline-end: 40px; overflow-wrap: break-word;font-family: Verdana, "Bitstream Vera Sans", Geneva, sans-serif !important;
                '>{{answer.post_body}}</pre></div>
                <div class='mentions' style='font-size: .8em!important;
                padding: 0;
                padding-left: 3%;
                display: table; 'id='{{answer.id}}'> </div>
    
    
    </div>
    </div>
    
    <br>
        {% endfor %}
    </div></div>
      </div>
    {% endfor %}
    <script>
        $(document).ready(function() {
        $('.container-heading').click(function() {
            $(this).find(".hidden").toggleClass('open');
        });
    });
    </script>
    {%endblock%}
</body>

</html>

obiadekchan/templates/obiadekchan/login.html
{% load static %}
<html>
        <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
                <meta name="description" content="">
                <meta name="author" content="">
                <link rel="icon" href="../../favicon.ico">
                <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/navbar-fixed-top/">
            <link rel="stylesheet" href="{% static 'css/styles.css' %}">
             <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

             <script src="//cdnjs.cloudflare.com/ajax/libs/x-editabl°ne/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>

            <title>Login</title>
            </head>
<body>
<form class="form-horizontal" role="form"  method="post" enctype="multipart/form-data">

    {% csrf_token %}<container>
        <input class="u-full-width" rows="3" type="text" name="username" style='border-radius:5px;border-style:solid;border-color:cornflowerblue;'/><br>
    </container>        <input class="u-full-width" rows="3" type="password" name="password"style='border-radius:5px;border-style:solid;border-color: cornflowerblue;'/>
<br>ujkkkkkkkkkkkkkk
           <button type="submit" value='post' class="btn btn-info">Submit</button>

     </form></div>
</div>
    </body>kkkkkkkkkkkkk
    </html>kkkkkkkkkkkkkk, kjjjjjnm0kkmoonj0,888888888888888

obiadekchan/templates/obiadekchan/mode.html
{% load static %}
<html>
        <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
                <meta name="description" content="">
                <meta name="author" content="">
                <link rel="icon" href="../../favicon.ico">
                <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/navbar-fixed-top/">
            <link rel="stylesheet" href="{% static 'css/styles.css' %}">
             <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

             <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
             <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
             <style>
                    table {
                      font-family: arial, sans-serif;
                      border-collapse: collapse;
                      width: 100%;
                    }
                    
                    td, th {
                      border: 1px solid #dddddd;
                      text-align: left;
                      padding: 8px;
                    }
                    
                    tr:nth-child(even) {
                      background-color: #dddddd;
                    }
                    </style>
                      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
                      <link rel="stylesheet" href="/resources/demos/style.css">
                      <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
                      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

                      <link rel="stylesheet" type="text/css" href="jquery.datetimepicker.min.css"/>

                      <script>
                      $( function() {
                        $( "#datepicker" ).datepicker();
                      } );
                      </script>
            <title>Moderator panel</title>
            </head>
            <body>
                    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
                            <div class="modal-dialog" role="document">
                              <div class="modal-content">
                          
                              </div>
                            </div>
                          </div>
                          <span style='float:right;'><a href='{% url "obiadekchan:logout" %}'>[Log out]</a></span>  <span style='float:right;'><a href='{% url "obiadekchan:history" %}'>[See users post history]</a></span> 

                <h2>Reported posts</h2>
                <table>
                    <tr>
                        <th>Post name</th>
                        <th>Post body</th>
                        <th>Poster ip</th>
                        <th>Report reason</th>
                        <th>Delete</th>
                        <th>Ban</th>
                        <th>Remove report</th>
                    </tr>
                    {%for post in posts%}
                    <tr>
                        <td>{{post.post_title}}</td>
                        <td>{{post.post_body|linebreaks}}</td>
                        <td>{{post.ip_address}}</td>
                        <td>{{post.rep_res}}</td>
                        <td><form method='post' >{% csrf_token %}<button type='submit' name='del_post' value='{{post.id}}'>Delete thread</button></form></td>
                        <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal{{post.id}}">
                                Ban user
                              </button>
                            </td>
                        <td><form method='post'>{% csrf_token %} <button type='submit' name='del_report' value='{{post.id}}'>Delete report</button> </form></td>
            
                    </tr>
                    <!-- Modal -->
<div class="modal fade" id="exampleModal{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Ban user</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form method='post'>{%csrf_token%}
                 <p>Reason: <input class="u-full-width" type="text" name="b_reason" style='border-radius:0px'/></p>
                    <p>Date when ban expires: <input type="datetime-local" class="datepicker" name='b_length' min="2019-12-23T00:00" required></p>
                    <!--  <p>{{banForm.length}}</p>
                    <p>{{banForm.reason}}</p>-->
                    <button type="submit" class="btn btn-primary" name='ban_ip' value='{{post.id}}'>Ban</button>
                </form>
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            
            </div>
          </div>
        </div>
      </div>
                    {%endfor%}
                </table>
                <br>
                   
                    <h2>Banned users</h2>
                    <table>
                    <tr>
                            <th>Banned ips</th>
                            <th>Ban reason</th>
                            <th>Banned post</th>
                            <th>Banned until:</th>
                            <th>Unban</th>
                        </tr>
                        {%for ban in banned%}
                    <tr>
                        <td>{{ban.ip_ad}}</td>
                        <td>{{ban.reason}}</td>
                        <td>{{ban.post_content|linebreaks}}</td>
                        <td>{{ban.length}}</td>
                        <td><form method='post'  >{% csrf_token %} <button type='submit' name='unban' value='{{ban.id}}' >Unban</form></td>
                    </tr>
                </table>
                    
                {%endfor%}
               
                </table>


            </body>
            </html>

obiadekchan/templates/obiadekchan/post_aapreview.html
{% load static %}
<html>
        <head>
     
        </head>
        <body>
{%block body%}

{%load thumbnail%}

<span class='preview' style=' display:inline-block; z-index:1;
        background: #ACD7DE;
        padding: 3px;  position: absolute;
        margin: 3px;overflow: hidden;
        width: fit-content;         top: -50%;
    left: 10%;
        height: fit-content; 
        clear: both; 
        '><span class='post' style='width: 100%;height: 100%;display: block;padding: 2;margin-right: 10;'>
    <div class='thread_title' style='    padding: 5px;
        background-color: #ACD7DE; 
       display: block;
position: relative;
'><input type='radio' name='rep_choice' value='{{post.id}}'></input>{%if post.post_title %} <span class='title'>{{post.post_title}}</span> {% endif %} {%if post.op_email%}
        <a href='mailto:{{post.op_email}}' style='color:darkgrey;'>Anonymouos</a> {%else%}
        <span class='name'> Anonymous</span> {%endif%}
        <span class='date'> {{post.date}} </span>
        <span class='post_number'> post number: <a href='#'>{{post.id}}</a> </span><span>  <a href='{% url "obiadekchan:thread" post.id %}'>[Reply]</a></span></div>

    {%if post.image%} {%thumbnail post.image "240" as im %}
    <a href='{{post.image.url}}' target="_blank" style='    float: left;
    margin-left: 20px;
    margin-right: 20px;
    margin-top: 3px;
    margin-bottom: 0;
    position: relative;
    display: block;
    margin-bottom: 20;
   '><img src='{{im.url}}' /></a>
    {%endthumbnail%} {%endif%}
    <pre style='
    heaight:100%;
    width:100%;
    display: block;
    white-space: pre-wrap;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 40px;
    margin-inline-end: 40px;
    overflow-wrap: break-word;
    font-family: Verdana, "Bitstream Vera Sans", Geneva, sans-serif !important; '>{{post.post_body}}</pre>
        
        </span>
</span>
{%endblock%}
</body>